#!/usr/bin/env python3
"""
fourier_analysis_qubits.py

Fourier / spectral analysis of per-qubit trajectories generated by the Heisenberg model.

Input format
------------
Expects a directory of pickles named like:
  TrueHist_Seed{seed}_N{N}_qubits({qmin}-{qmax})_op({op})_dt{dt_underscore}.pkl
with payload:
  {
    "N": int, "dt": float, "T": int, "op": str, "seed": int,
    "qubits": [int,...],
    "series": { qubit_index: 1D array-like of float }
  }

What it does
------------
- Loads all matching pickles from SRC_DIR (optionally verifying N/op/dt).
- For each qubit index present across the files:
  * Collects time series from each file
  * Runs Fourier analysis (SciPy Welch by default) to estimate PSD for each
  * Averages PSDs across files/seeds and computes std & 95% CI
- Saves:
  * One OVERLAY plot comparing mean PSD across qubits
  * One PER-QUIT plot with mean PSD ± 95% CI
  * CSV per-qubit with (f, mean_psd, std_psd, se_psd, n)
  * A summary CSV with peak frequency and integrated power

Dependencies
------------
numpy, pandas, matplotlib, scipy

Notes
-----
- Welch PSD is recommended for noisy trajectories and averaging across seeds.
- All files are expected to share the same dt, N, and op unless SKIP_CHECKS=True.
"""

import os
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from glob import glob
from typing import Dict, Tuple, Any, List
from collections import defaultdict

from scipy.signal import welch, get_window


# ------------------------- Loading & checks -------------------------
def load_series(path: str) -> Tuple[Dict[str, Any], Dict[int, np.ndarray]]:
    with open(path, "rb") as f:
        payload = pickle.load(f)
    meta = {k: payload.get(k) for k in ["N", "dt", "op", "T", "seed", "qubits"]}
    series = payload.get("series", {})
    normalized: Dict[int, np.ndarray] = {}
    for k, v in series.items():
        try:
            ik = int(k)
        except Exception:
            s = str(k)
            digits = "".join(ch for ch in s if ch.isdigit())
            ik = int(digits) if digits else k
        a = np.asarray(v).ravel().astype(float)
        normalized[ik] = a
    return meta, normalized


# ------------------------- Spectral estimation -------------------------
def compute_psd_welch(x: np.ndarray, dt: float, nperseg: int, noverlap: int = None, window: str = "hann") -> Tuple[np.ndarray, np.ndarray]:
    """
    Welch PSD estimate (units of power/Hz). Returns (frequencies, Pxx).
    """
    fs = 1.0 / dt
    if noverlap is None:
        noverlap = nperseg // 2
    f, pxx = welch(
        x,
        fs=fs,
        window=get_window(window, nperseg),
        nperseg=nperseg,
        noverlap=noverlap,
        detrend="constant",
        return_onesided=True,
        scaling="density",
        average="mean",
    )
    return f, pxx


def compute_fft_amplitude(x: np.ndarray, dt: float) -> Tuple[np.ndarray, np.ndarray]:
    """
    Real FFT amplitude spectrum (|X(f)|). Returns (frequencies, amplitudes).
    Not averaged; mainly for quick inspection. Welch is preferred for PSDs.
    """
    x = np.asarray(x)
    n = x.size
    fs = 1.0 / dt
    # Remove mean to suppress DC spike
    x = x - np.mean(x)
    X = np.fft.rfft(x)
    amp = np.abs(X) / n
    freqs = np.fft.rfftfreq(n, d=dt)
    return freqs, amp


# ------------------------- Aggregation across files -------------------------
def aggregate_psd_across_files(
    paths: List[str],
    expect_N: int = None,
    expect_op: str = None,
    expect_dt: float = None,
    skip_checks: bool = False,
    method: str = "welch",
    nperseg_hint: int = 256,
    window: str = "hann"
):
    """
    Returns:
      qubit_results: dict[q] -> {
         'f': frequency array,
         'psd_list': list of PSD arrays per file,
         'mean': mean PSD,
         'std': std PSD,
         'se': std/sqrt(n),
         'n': number of spectra
      }
      meta_out: dict with 'N', 'op', 'dt', 'files_used'
    """
    # Gather per-qubit series across files (and track min lengths)
    per_qubit_series: Dict[int, List[np.ndarray]] = defaultdict(list)
    used = 0
    dt_ref = None
    N_ref = None
    op_ref = None
    min_len = None

    for p in sorted(paths):
        try:
            meta, series = load_series(p)
        except Exception as e:
            print(f"[skip] {p}: load error: {e}")
            continue

        if not skip_checks:
            if (expect_N is not None and meta.get("N") != expect_N) or \
               (expect_op is not None and meta.get("op") != expect_op) or \
               (expect_dt is not None and abs(meta.get("dt") - expect_dt) > 1e-12):
                print(f"[skip] {p}: metadata mismatch (got N={meta.get('N')}, op={meta.get('op')}, dt={meta.get('dt')})")
                continue

        # establish refs
        if dt_ref is None: dt_ref = meta.get("dt")
        if N_ref  is None: N_ref  = meta.get("N")
        if op_ref is None: op_ref = meta.get("op")

        # collect
        for q, arr in series.items():
            arr = np.asarray(arr, dtype=float).ravel()
            per_qubit_series[q].append(arr)
            L = arr.size
            min_len = L if min_len is None else min(min_len, L)
        used += 1

    if used == 0:
        print("[aggregate] No files used; check metadata or source directory.")
        return {}, {"N": None, "op": None, "dt": None, "files_used": 0}

    # Decide nperseg based on min available length
    if method == "welch":
        if min_len is None or min_len < 16:
            raise ValueError("Time series too short for Welch PSD.")
        nperseg = min(nperseg_hint, min_len)
        if nperseg < 16:
            nperseg = min_len  # fallback
        print(f"[aggregate] Using Welch with nperseg={nperseg} (min_len={min_len})")
    else:
        nperseg = None

    results = {}
    for q in sorted(per_qubit_series.keys()):
        specs = []
        freqs = None
        for x in per_qubit_series[q]:
            if method == "welch":
                f, Pxx = compute_psd_welch(x, dt_ref, nperseg=nperseg, window=window)
                if freqs is None: freqs = f
                specs.append(Pxx)
            else:
                f, amp = compute_fft_amplitude(x, dt_ref)
                if freqs is None: freqs = f
                specs.append(amp)

        arr = np.vstack(specs)  # shape: (num_files, num_freqs)
        mean = arr.mean(axis=0)
        std  = arr.std(axis=0, ddof=1) if arr.shape[0] > 1 else np.zeros_like(mean)
        se   = std / np.sqrt(arr.shape[0]) if arr.shape[0] > 0 else np.zeros_like(mean)

        results[q] = {
            "f": freqs,
            "psd_list": arr,
            "mean": mean,
            "std": std,
            "se": se,
            "n": arr.shape[0],
        }

    meta_out = {"N": N_ref, "op": op_ref, "dt": dt_ref, "files_used": used, "method": method}
    return results, meta_out


# ------------------------- Plotting & export -------------------------
def ensure_dir(d: str):
    os.makedirs(d, exist_ok=True)
    return d

def plot_overlay_qubits(results: Dict[int, Dict[str, np.ndarray]], out_dir: str, title: str = None, log_y: bool = True):
    ensure_dir(out_dir)
    plt.figure(figsize=(9, 6))
    for q in sorted(results.keys()):
        f = results[q]["f"]
        y = results[q]["mean"]
        if log_y:
            plt.semilogy(f, y, label=f"q{q}")
        else:
            plt.plot(f, y, label=f"q{q}")
    plt.xlabel("Frequency (Hz)")
    plt.ylabel("PSD (power/Hz)" if title is None else title)
    plt.title(title or "Mean PSD across qubits")
    plt.legend(loc="best")
    plt.grid(True, which="both", ls=":")
    out_path = os.path.join(out_dir, "overlay_qubits_mean_psd.png")
    plt.savefig(out_path, bbox_inches="tight", dpi=144)
    plt.close()
    return out_path

def plot_per_qubit_ci(results: Dict[int, Dict[str, np.ndarray]], out_dir: str, ci: float = 0.95, log_y: bool = True):
    ensure_dir(out_dir)
    saved = []
    z = 1.96 if abs(ci - 0.95) < 1e-6 else 1.96  # simple support for 95%
    for q in sorted(results.keys()):
        f = results[q]["f"]
        m = results[q]["mean"]
        se = results[q]["se"]
        lo = np.maximum(m - z * se, 0.0)
        hi = m + z * se

        plt.figure(figsize=(9, 6))
        if log_y:
            plt.semilogy(f, m, label=f"q{q} mean PSD")
            # plot CI as thin lines (avoid fill on log scale for simplicity)
            plt.semilogy(f, lo, linestyle="--", alpha=0.7, label="95% CI (low)")
            plt.semilogy(f, hi, linestyle="--", alpha=0.7, label="95% CI (high)")
        else:
            plt.plot(f, m, label=f"q{q} mean PSD")
            plt.fill_between(f, lo, hi, alpha=0.2, label="95% CI")

        plt.xlabel("Frequency (Hz)")
        plt.ylabel("PSD (power/Hz)")
        plt.title(f"q{q} Mean PSD ± 95% CI (n={results[q]['n']})")
        plt.legend(loc="best")
        plt.grid(True, which="both", ls=":")
        out_path = os.path.join(out_dir, f"psd_q{q}_mean_ci.png")
        plt.savefig(out_path, bbox_inches="tight", dpi=144)
        plt.close()
        saved.append(out_path)
    return saved

def export_csvs(results: Dict[int, Dict[str, np.ndarray]], out_dir: str):
    ensure_dir(out_dir)
    saved = []
    for q in sorted(results.keys()):
        df = pd.DataFrame({
            "f_Hz": results[q]["f"],
            "mean_psd": results[q]["mean"],
            "std_psd": results[q]["std"],
            "se_psd": results[q]["se"],
            "n": results[q]["n"],
        })
        path = os.path.join(out_dir, f"psd_q{q}.csv")
        df.to_csv(path, index=False)
        saved.append(path)
    return saved

def summarize_peaks(results: Dict[int, Dict[str, np.ndarray]], out_dir: str):
    ensure_dir(out_dir)
    rows = []
    for q in sorted(results.keys()):
        f = results[q]["f"]
        m = results[q]["mean"]
        peak_idx = int(np.argmax(m))
        peak_f = float(f[peak_idx])
        # Integrated power over positive freqs: approximates variance
        area = float(np.trapz(m, f))
        rows.append({"qubit": f"q{q}", "peak_freq_Hz": peak_f, "integrated_power": area, "n_spectra": int(results[q]["n"])})
    df = pd.DataFrame(rows)
    path = os.path.join(out_dir, "summary_peaks.csv")
    df.to_csv(path, index=False)
    return path


# ------------------------- Main entry (edit variables here) -------------------------
if __name__ == "__main__":
    # ======= USER SETTINGS =======
    SRC_DIR           = "./true_hist"         # folder with TrueHist_*.pkl from your generator
    OUT_DIR           = "./fourier_out"       # output folder for plots/CSVs
    EXPECT_N          = 5                     # set to None to skip check
    EXPECT_OP         = "sz"                  # set to None to skip check
    EXPECT_DT         = 0.2                   # set to None to skip check
    SKIP_CHECKS       = False                 # if True, will include mixed metadata (not recommended)

    METHOD            = "fft"               # "welch" (recommended) or "fft"
    NPERSEG_HINT      = 256                   # Welch segment length hint (auto-truncated to min series length)
    WINDOW            = "hann"                # Welch window
    LOG_Y             = True                  # semilogy for PSD plots
    CI_LEVEL          = 0.95                  # 95% CI shading/lines

    
    # ======= RUN =======
    os.makedirs(OUT_DIR, exist_ok=True)
    paths = sorted(glob(os.path.join(SRC_DIR, "TrueHist_*.pkl")))
    if not paths:
        print(f"[main] No TrueHist_*.pkl found in {SRC_DIR}. Aborting.")
        raise SystemExit(0)

    
    # paths = paths[:]
    # ======= SANITY CHECK: subplots for qubits 0–4 =======
    # first_file = paths[-686]
    first_file = paths[0]
    print(f"[sanity] Plotting raw trajectories from {first_file}")
    _, first_series = load_series(first_file)

    qubits_to_show = [q for q in sorted(first_series.keys()) if q <= 4]
    n_q = len(qubits_to_show)

    fig, axs = plt.subplots(n_q, 1, figsize=(10, 2.5 * n_q), sharex=True)
    if n_q == 1:
        axs = [axs]  # handle single-axis case

    for ax, q in zip(axs, qubits_to_show):
        y = first_series[q]
        t = np.arange(len(y)) * EXPECT_DT if EXPECT_DT is not None else np.arange(len(y))
        ax.plot(t, y, label=f"q{q}", color=f"C{q}")
        ax.set_ylabel("Observable")
        ax.set_title(f"Qubit {q}")
        ax.grid(True, ls=":")
        ax.legend(loc="best")

    axs[-1].set_xlabel("Time")

    sanity_path = os.path.join(OUT_DIR, "sanity_first_file_qubits0-4.png")
    plt.tight_layout()
    plt.savefig(sanity_path, bbox_inches="tight", dpi=144)
    plt.close()
    print(f"[sanity] Saved sanity check subplot figure: {sanity_path}")

    results, meta = aggregate_psd_across_files(
        paths,
        expect_N=EXPECT_N,
        expect_op=EXPECT_OP,
        expect_dt=EXPECT_DT,
        skip_checks=SKIP_CHECKS,
        method=METHOD,
        nperseg_hint=NPERSEG_HINT,
        window=WINDOW
    )

    if not results:
        print("[main] No results produced.")
        raise SystemExit(0)

    # Exports
    overlay_path = plot_overlay_qubits(results, OUT_DIR, title=None, log_y=LOG_Y)
    per_qubit_imgs = plot_per_qubit_ci(results, OUT_DIR, ci=CI_LEVEL, log_y=LOG_Y)
    csv_paths = export_csvs(results, OUT_DIR)
    summary_path = summarize_peaks(results, OUT_DIR)

    print("[main] Done.")
    print(f"  Files used: {meta.get('files_used')}  |  dt={meta.get('dt')}  |  N={meta.get('N')}  |  op={meta.get('op')}  |  method={meta.get('method')}")
    print(f"  Overlay plot: {overlay_path}")
    print(f"  Per-qubit plots: {len(per_qubit_imgs)} written")
    print(f"  CSV exports: {len(csv_paths)} written")
    print(f"  Summary: {summary_path}")
